version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-go:1.0.0
    ports:
      - "8080:8080"
    container_name: backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
