version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-go:1.0.0
    ports:
      - "8080:8080"
    container_name: backend
    volumes:
      - db-data:/app/db
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-react:1.0.0
    ports:
      - "3000:80"
    container_name: frontend
    networks:
      - app-network
    depends_on:
      - backend

  database:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    volumes:
      - db-data:/data
      - ./database/init.sql:/data/init.sql
    entrypoint: |
      sh -c "
        sqlite3 /data/database.db < /data/init.sql && 
        tail -f /dev/null"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
