version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-go:1.0.0
    ports:
      - "8080:8080"
    container_name: backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-react:1.0.0
    ports:
      - "3000:80"
    container_name: frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
